name: "EasyScript"
version: "1.1"
main: "org.cyberiantiger.minecraft.easyscript.EasyScript"
website: "http://dev.bukkit.org/server-mods/easyscript/"
commands:
  script:
    description: 执行一个逻辑
    usage: /script <name> <args>
    permission: easyscript.script
  scriptreload:
    description: 重新加载逻辑
    usage: /scriptreload
    permission: easyscript.reload